### ISSUE TITLE
Where to set that custom class ?

### ISSUE THREAD

**Issue by notlsd** [wayou/hexo-image-caption#1]

**Comment by wayou** [comment]
the readme explains:
```yaml
# add caption for iamges
image_caption:
  enable: true #false to disable
  class_name: #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'
```
